Balance staged Gamma video dynamics loss

diff --git a/osmo_workflows/robofactory/train_liftbarrier_gamma_staged.yaml b/osmo_workflows/robofactory/train_liftbarrier_gamma_staged.yaml
--- a/osmo_workflows/robofactory/train_liftbarrier_gamma_staged.yaml
+++ b/osmo_workflows/robofactory/train_liftbarrier_gamma_staged.yaml
@@ -369,6 +369,7 @@ workflow:
             require_code_marker \
               scripts/train/robofactory_bimanual_training.sh \
               "DATASET_SHARD_SAMPLING_RATE" \
+              "dynamics_loss_weight" \
               "gripper_binary_action_loss_weight" \
               "ROPE_AGENT_DIM" \
               "GLOBAL_VIDEO_DROPOUT_PROB" \
@@ -442,20 +443,39 @@ workflow:
             export SAVE_STEPS="${SAVE_STEPS:-{{save_steps}}}"
             export SAVE_TOTAL_LIMIT="${SAVE_TOTAL_LIMIT:-{{save_total_limit}}}"
             export LEARNING_RATE="${LEARNING_RATE:-{{learning_rate}}}"
-            export ACTION_LOSS_WEIGHT="${ACTION_LOSS_WEIGHT:-5.0}"
-            export GRIPPER_ACTION_LOSS_WEIGHT="${GRIPPER_ACTION_LOSS_WEIGHT:-6.0}"
-            export GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_CLOSE_ACTION_LOSS_WEIGHT:-4.0}"
+            export BASE_DYNAMICS_LOSS_WEIGHT="${DYNAMICS_LOSS_WEIGHT:-1.0}"
+            export BASE_ACTION_LOSS_WEIGHT="${ACTION_LOSS_WEIGHT:-5.0}"
+            export BASE_GRIPPER_ACTION_LOSS_WEIGHT="${GRIPPER_ACTION_LOSS_WEIGHT:-6.0}"
+            export BASE_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_CLOSE_ACTION_LOSS_WEIGHT:-4.0}"
             export GRIPPER_CLOSE_THRESHOLD="${GRIPPER_CLOSE_THRESHOLD:-0.0}"
             export GRIPPER_ACTION_DIMS="${GRIPPER_ACTION_DIMS:-7}"
-            export GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="${GRIPPER_CLEAN_ACTION_LOSS_WEIGHT:-2.0}"
-            export GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT:-4.0}"
+            export BASE_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="${GRIPPER_CLEAN_ACTION_LOSS_WEIGHT:-2.0}"
+            export BASE_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT:-4.0}"
             export GRIPPER_CLEAN_MAX_SIGMA="${GRIPPER_CLEAN_MAX_SIGMA:-0.75}"
-            export GRIPPER_BINARY_ACTION_LOSS_WEIGHT="${GRIPPER_BINARY_ACTION_LOSS_WEIGHT:-4.0}"
-            export GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT:-6.0}"
+            export BASE_GRIPPER_BINARY_ACTION_LOSS_WEIGHT="${GRIPPER_BINARY_ACTION_LOSS_WEIGHT:-4.0}"
+            export BASE_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="${GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT:-6.0}"
             export GRIPPER_BINARY_LOGIT_SCALE="${GRIPPER_BINARY_LOGIT_SCALE:-4.0}"
             export GRIPPER_BINARY_MAX_SIGMA="${GRIPPER_BINARY_MAX_SIGMA:-0.75}"
-            export ACTION_PREFIX_LOSS_WEIGHT="${ACTION_PREFIX_LOSS_WEIGHT:-2.0}"
+            export BASE_ACTION_PREFIX_LOSS_WEIGHT="${ACTION_PREFIX_LOSS_WEIGHT:-2.0}"
             export ACTION_PREFIX_LOSS_LEN="${ACTION_PREFIX_LOSS_LEN:-8}"
+            export STAGE1_DYNAMICS_LOSS_WEIGHT="${STAGE1_DYNAMICS_LOSS_WEIGHT:-2.0}"
+            export STAGE1_ACTION_LOSS_WEIGHT="${STAGE1_ACTION_LOSS_WEIGHT:-1.0}"
+            export STAGE1_GRIPPER_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_ACTION_LOSS_WEIGHT:-2.0}"
+            export STAGE1_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT:-2.0}"
+            export STAGE1_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT:-0.5}"
+            export STAGE1_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT:-2.0}"
+            export STAGE1_GRIPPER_BINARY_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_BINARY_ACTION_LOSS_WEIGHT:-1.0}"
+            export STAGE1_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="${STAGE1_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT:-2.0}"
+            export STAGE1_ACTION_PREFIX_LOSS_WEIGHT="${STAGE1_ACTION_PREFIX_LOSS_WEIGHT:-1.0}"
+            export STAGE2_DYNAMICS_LOSS_WEIGHT="${STAGE2_DYNAMICS_LOSS_WEIGHT:-$BASE_DYNAMICS_LOSS_WEIGHT}"
+            export STAGE2_ACTION_LOSS_WEIGHT="${STAGE2_ACTION_LOSS_WEIGHT:-$BASE_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_BINARY_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_BINARY_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_BINARY_ACTION_LOSS_WEIGHT}"
+            export STAGE2_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="${STAGE2_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT:-$BASE_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT}"
+            export STAGE2_ACTION_PREFIX_LOSS_WEIGHT="${STAGE2_ACTION_PREFIX_LOSS_WEIGHT:-$BASE_ACTION_PREFIX_LOSS_WEIGHT}"
             export FIRST_CLOSE_JOINT_LOSS_WEIGHT="${FIRST_CLOSE_JOINT_LOSS_WEIGHT:-1.0}"
             export FIRST_CLOSE_JOINT_LOSS_WINDOW_BEFORE="${FIRST_CLOSE_JOINT_LOSS_WINDOW_BEFORE:-0}"
             export FIRST_CLOSE_JOINT_LOSS_WINDOW_AFTER="${FIRST_CLOSE_JOINT_LOSS_WINDOW_AFTER:-0}"
@@ -605,6 +625,38 @@ workflow:
               CACHE_OUTPUT_S3_URI="s3://GearHome/users/xianzhef/oci-migration/dreamzero_s3cache/bootstrap_checkpoints/${RUN_NAME}"
             }
 
+            configure_stage_loss_weights() {
+              stage_prefix="$1"
+              case "$stage_prefix" in
+                stage1)
+                  export DYNAMICS_LOSS_WEIGHT="$STAGE1_DYNAMICS_LOSS_WEIGHT"
+                  export ACTION_LOSS_WEIGHT="$STAGE1_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_BINARY_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_BINARY_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="$STAGE1_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT"
+                  export ACTION_PREFIX_LOSS_WEIGHT="$STAGE1_ACTION_PREFIX_LOSS_WEIGHT"
+                  ;;
+                stage2)
+                  export DYNAMICS_LOSS_WEIGHT="$STAGE2_DYNAMICS_LOSS_WEIGHT"
+                  export ACTION_LOSS_WEIGHT="$STAGE2_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLOSE_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_CLOSE_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLEAN_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_CLEAN_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_BINARY_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_BINARY_ACTION_LOSS_WEIGHT"
+                  export GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT="$STAGE2_GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT"
+                  export ACTION_PREFIX_LOSS_WEIGHT="$STAGE2_ACTION_PREFIX_LOSS_WEIGHT"
+                  ;;
+                *)
+                  echo "ERROR: unknown stage loss prefix ${stage_prefix}" >&2
+                  exit 10
+                  ;;
+              esac
+            }
+
             run_training_stage() {
               stage_label="$1"
               stage_run_name="$2"
@@ -612,8 +664,10 @@ workflow:
               sparse_hub="$4"
               stage_pretrained_dir="$5"
               stage_output_dir="$6"
+              stage_loss_prefix="$7"
 
               configure_stage_paths "$stage_run_name"
+              configure_stage_loss_weights "$stage_loss_prefix"
               export MAX_STEPS="$stage_max_steps"
               export USE_SPARSE_HUB_ATTENTION="$sparse_hub"
               export PRETRAINED_DIR="$stage_pretrained_dir"
@@ -635,6 +689,12 @@ workflow:
               echo "PRETRAINED_DIR=$PRETRAINED_DIR"
               echo "MAX_STEPS=$MAX_STEPS"
               echo "GRIPPER_ACTION_DIMS=$GRIPPER_ACTION_DIMS"
+              echo "DYNAMICS_LOSS_WEIGHT=$DYNAMICS_LOSS_WEIGHT"
+              echo "ACTION_LOSS_WEIGHT=$ACTION_LOSS_WEIGHT"
+              echo "GRIPPER_ACTION_LOSS_WEIGHT=$GRIPPER_ACTION_LOSS_WEIGHT"
+              echo "GRIPPER_CLOSE_ACTION_LOSS_WEIGHT=$GRIPPER_CLOSE_ACTION_LOSS_WEIGHT"
+              echo "GRIPPER_CLEAN_ACTION_LOSS_WEIGHT=$GRIPPER_CLEAN_ACTION_LOSS_WEIGHT"
+              echo "GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT=$GRIPPER_CLEAN_CLOSE_ACTION_LOSS_WEIGHT"
               echo "GRIPPER_BINARY_ACTION_LOSS_WEIGHT=$GRIPPER_BINARY_ACTION_LOSS_WEIGHT"
               echo "GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT=$GRIPPER_BINARY_CLOSE_ACTION_LOSS_WEIGHT"
               echo "GRIPPER_BINARY_LOGIT_SCALE=$GRIPPER_BINARY_LOGIT_SCALE"
@@ -674,7 +734,8 @@ workflow:
               "$STAGE1_MAX_STEPS" \
               "false" \
               "$DREAMZERO_DROID_PRETRAINED_DIR" \
-              "$STAGE1_OUTPUT_DIR"
+              "$STAGE1_OUTPUT_DIR" \
+              "stage1"
 
             STAGE1_CKPT="$(latest_complete_checkpoint "$STAGE1_OUTPUT_DIR" || true)"
             if [ -z "$STAGE1_CKPT" ]; then
@@ -689,7 +750,8 @@ workflow:
               "$STAGE2_MAX_STEPS" \
               "true" \
               "$STAGE1_CKPT" \
-              "$STAGE2_OUTPUT_DIR"
+              "$STAGE2_OUTPUT_DIR" \
+              "stage2"
 
             echo "Staged Gamma training complete."
 
